-- MySQL Script generated by MySQL Workbench
-- Mon Aug 29 19:30:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pharmacy` ;

-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharmacy` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pharmacy` ;

-- -----------------------------------------------------
-- Table `pharmacy`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pharmacy`.`users` (
                                                  `user_id` INT NOT NULL AUTO_INCREMENT,
                                                  `user_name` VARCHAR(45) NOT NULL,
                                                  `login` VARCHAR(45) NOT NULL,
                                                  `password` VARCHAR(45) NOT NULL,
                                                  `email` VARCHAR(45) NOT NULL,
                                                  `phone` VARCHAR(45) NOT NULL,
                                                  `money_amount` DECIMAL(10,2) NOT NULL,
                                                  PRIMARY KEY (`user_id`))
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pharmacy`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`orders` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pharmacy`.`orders` (
                                                   `order_id` INT NOT NULL AUTO_INCREMENT,
                                                   `user_id` INT NOT NULL,
                                                   `address` VARCHAR(45) NULL,
                                                   `status` ENUM('CREATING', 'IN_PROCESS', 'CLOSED') NOT NULL,
                                                   `date_open` TIMESTAMP NOT NULL,
                                                   `date_close` TIMESTAMP NULL,
                                                   `full_cost` DECIMAL(10,2) NOT NULL,
                                                   PRIMARY KEY (`order_id`),
                                                   INDEX `users_idx` (`user_id` ASC) VISIBLE,
                                                   CONSTRAINT `users`
                                                       FOREIGN KEY (`user_id`)
                                                           REFERENCES `pharmacy`.`users` (`user_id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pharmacy`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pharmacy`.`products` (
                                                     `product_id` INT NOT NULL AUTO_INCREMENT,
                                                     `product_name` VARCHAR(45) NOT NULL,
                                                     `details` TEXT NOT NULL,
                                                     `price` DECIMAL(5,2) NOT NULL,
                                                     `type` ENUM('ENTERAL', 'EXTERNAL', 'INHALATION') NOT NULL,
                                                     `photo` BLOB NULL,
                                                     `goods_quantity` INT NOT NULL,
                                                     `need_prescription` ENUM('TRUE', 'FALSE') NOT NULL,
                                                     PRIMARY KEY (`product_id`))
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pharmacy`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`order_product` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pharmacy`.`order_product` (
                                                          `order_product_id` INT NOT NULL AUTO_INCREMENT,
                                                          `order_id` INT NOT NULL,
                                                          `product_id` INT NOT NULL,
                                                          `quantity` INT NOT NULL,
                                                          `volume` ENUM('20ML', '50ML', '100ML') NOT NULL,
                                                          `order_product_price` DECIMAL(10,2) NOT NULL,
                                                          INDEX `orders_idx` (`order_id` ASC) VISIBLE,
                                                          INDEX `products_idx` (`product_id` ASC) VISIBLE,
                                                          PRIMARY KEY (`order_product_id`),
                                                          CONSTRAINT `orders`
                                                              FOREIGN KEY (`order_id`)
                                                                  REFERENCES `pharmacy`.`orders` (`order_id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION,
                                                          CONSTRAINT `products`
                                                              FOREIGN KEY (`product_id`)
                                                                  REFERENCES `pharmacy`.`products` (`product_id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pharmacy`.`recipe_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`recipe_requests` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pharmacy`.`recipe_requests` (
                                                            `recipe_requests_id` INT NOT NULL AUTO_INCREMENT,
                                                            `client_id` INT NOT NULL,
                                                            `doctor_id` INT NOT NULL,
                                                            `response` ENUM('TRUE', 'FALSE') NULL,
                                                            `product_id` INT NOT NULL,
                                                            PRIMARY KEY (`recipe_requests_id`),
                                                            INDEX `current_client_id_idx` (`client_id` ASC) VISIBLE,
                                                            INDEX `current_doctor_id_idx` (`doctor_id` ASC) VISIBLE,
                                                            CONSTRAINT `current_client_id`
                                                                FOREIGN KEY (`client_id`)
                                                                    REFERENCES `pharmacy`.`users` (`user_id`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION,
                                                            CONSTRAINT `current_doctor_id`
                                                                FOREIGN KEY (`doctor_id`)
                                                                    REFERENCES `pharmacy`.`users` (`user_id`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pharmacy`.`access_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`access_level` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pharmacy`.`access_level` (
                                                         `user_id` INT NOT NULL,
                                                         `access_level` ENUM('CLIENT', 'PHARMACIST', 'DOCTOR') NOT NULL,
                                                         PRIMARY KEY (`user_id`),
                                                         CONSTRAINT `current_user_id`
                                                             FOREIGN KEY (`user_id`)
                                                                 REFERENCES `pharmacy`.`users` (`user_id`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
